definitions:
  dto.CreateAccount:
    properties:
      email:
        example: abc@sample.com
        type: string
      hire_date:
        example: "2021-08-17"
        type: string
      id:
        example: simson
        type: string
      name:
        example: 홍길동
        type: string
      password:
        example: "1234"
        type: string
      phone_number:
        example: 010-1234-1234
        type: string
      work_code:
        example: 1
        type: integer
    type: object
  dto.Login:
    properties:
      id:
        example: simson
        type: string
      password:
        example: "1234"
        type: string
    type: object
  dto.Token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
info:
  contact: {}
paths:
  /account:
    post:
      consumes:
      - application/json
      description: 회원가입
      parameters:
      - description: create account
        in: body
        name: Account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create Account
      tags:
      - Account
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Token'
      summary: Login
      tags:
      - Login
swagger: "2.0"
